### ISSUE TITLE
Center of pie chart is misaligned

### ISSUE THREAD

**Issue by switz** [recharts/recharts#1017]
## Do you want to request a feature or report a bug?
Bug

## What is the current behavior?
The cells of a pie chart do not meet at the true center of the circle. They are imbalanced. This is very visible when adding a stroke of the same color to each cell, but is also noticeable even when using a default transparent stroke.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/qbmg1567/).
<img width="180" alt="screen shot 2017-11-15 at 3 48 41 pm" src="https://user-images.githubusercontent.com/990166/32860559-f0891444-ca1f-11e7-9380-340fac3b25c7.png"> <img width="179" alt="screen shot 2017-11-15 at 4 16 10 pm" src="https://user-images.githubusercontent.com/990166/32860668-51b93e10-ca20-11e7-87c1-32de4a213a45.png">

## What is the expected behavior?
The pie chart cells should align properly in the true center of the circle.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Beta1. Not sure if this worked previously as this is my first time working with Recharts. Currently running Chrome stable latest on Mac.

**Comment by TylerBissonSlalom** [comment]
@xile611 , @switz was this fixed in a specific rechart release? I'm seeing it on 2.15.4.

**Comment by PavelVanecek** [comment]
@TylerBissonSlalom I recommend to update to 3.x first and see if you can reproduce there.

**Comment by auprogrammer92** [comment]
Hi. I'm on the same project as Tyler and we're still seeing this. 

<img width="726" height="586" alt="Image" src="https://github.com/user-attachments/assets/c55c97c3-613e-4e0e-ac64-dc24e29a79b9" />

**Comment by PavelVanecek** [comment]
Which version are you using @auprogrammer92 ?

**Comment by auprogrammer92** [comment]
@PavelVanecek 3.8.1

**Comment by PavelVanecek** [comment]
Can you share a reproduction please? I can't see that problem on our charts

**Comment by auprogrammer92** [comment]
<img width="1171" height="644" alt="Image" src="https://github.com/user-attachments/assets/5d535c98-677b-4bde-a90c-c8c87ffe289a" />

**Comment by auprogrammer92** [comment]
@PavelVanecek 
Is there an update on this?

**Comment by PavelVanecek** [comment]
@auprogrammer92 It would be a great help if you could share your code next to the screenshot. Without the code I have nowhere to start. We have many Pie examples on our website and all are perfectly centered so I don't know where to go and search for the problem.

**Comment by auprogrammer92** [comment]
Here ya go:

<img width="559" height="460" alt="Image" src="https://github.com/user-attachments/assets/94e9afbb-544e-4e7e-90da-d8062a1d37e9" />

Goes away when all slices use a single, uniform stroke color (e.g., white) instead of matching each slice’s individual fill color.

<img width="510" height="449" alt="Image" src="https://github.com/user-attachments/assets/d8776ad3-b476-46e9-8116-d87aa0d76e97" />

```tsx
"use client";

import * as React from "react";

import { Cell, Legend, Pie, PieChart as RCPieChart, Tooltip } from "recharts";

const data = [
  { name: "A", value: 6800 },
  { name: "B", value: 5400 },
  { name: "C", value: 2100 },
  { name: "D", value: 900 },
  { name: "E", value: 830 },
];

const COLORS = ["#E87722", "#5B748A", "#0B3A53", "#7A9A01", "#1AA3A3"];

const PieChartBug = () => {
  return (
    <RCPieChart width={500} height={400}>
      <Pie
        data={data}
        cx="50%"
        cy="50%"
        outerRadius={140}
        dataKey="value"
        nameKey="name"
        label
        stroke="#ffffff"
        strokeWidth={3}
      >
        {data.map((entry, index) => (
          <Cell
            key={`${entry.name}-${index}`}
            fill={COLORS[index]}
            stroke={COLORS[index]} // 👈 critical to reproduce issue
          />
        ))}
      </Pie>

      <Tooltip />
      <Legend />
    </RCPieChart>
  );
};

export default PieChartBug;
```

**Comment by PavelVanecek** [comment]
Ah you added strokes. Well they are centered but if you add a stroke that makes the pie slices visibly larger. And because the browser engine is panting them one at a time, the second pie slice draws on top of the first and hides part of it.
Remove the stroke and you're done (`strokeWidth={0}`)

**Comment by PavelVanecek** [comment]
If you want to have different stroke color on the slices then that will be a bit more challenging because SVG doesn't have stroke-alignment property.

You can use gradient like here: https://recharts.github.io/en-US/examples/PieWithGradient/

Or you can use double width stroke plus `paint-order` plus masking/clipping like this: https://alexwlchan.net/2021/inner-outer-strokes-svg/
