### ISSUE TITLE
YAxis domain throws exception "[DecimalError] Invalid argument: NaN"

### ISSUE THREAD

**Issue by yambakshi** [recharts/recharts#1738]
Setting **YAxis**' _domain_ property throws the following exception:
`Uncaught Error: [DecimalError] Invalid argument: NaN`
`    at new Decimal (decimal.js:1876)`
`    at getTickValuesFixedDomainFn (getNiceTickValues.js:303)`
`    at utils.js:146`
`    at getTicksOfScale (ChartUtils.js:880)`
`    at CartesianUtils.js:69`
`    at Array.reduce (<anonymous>)`
`    at formatAxisMap (CartesianUtils.js:40)`
`    at generateCategoricalChart.js:1429`
`    at Array.forEach (<anonymous>)`
`    at CategoricalChartWrapper.updateStateOfAxisMapsOffsetAndStackGroups`
`(generateCategoricalChart.js:1428)`

The exception isn't thrown when setting **YAxis**' _domain_ to **[0, 'auto']**.
The exception isn't thrown when using **XAxis**.
Every other domain fails (**[0, 100], [0, 'dataMax']**, **[0, 'dataMax - 100']**).

Here's the code:
`<AreaChart width={1780} height={433} data={data}>`
`<CartesianGrid strokeWidth={0.2} vertical={false}/>`
`<YAxis tick={{fill: '#474a57'}} axisLine={false} interval="preserveStartEnd" tickCount={11} domain={[0, 100]} tickSize={0} />`
`<Area strokeWidth={1.5} type="linear" dataKey="key1" stroke={"url(#stroke1)"} fill={"url(#fill1)"} />`
`<Area strokeWidth={1.5} type="linear" dataKey="key2" stroke={"url(#stroke2)"} fill={"url(#fill2)"} />`
`</AreaChart>`

I've encountered the same exception on **recharts** versions **1.4.1** and **1.6.0** on Google Chrome.

**Comment by xile611** [comment]
@yambakshi Can you create an online demo to reproduce your problem? I can't reproduce it.

**Comment by imjustd** [comment]
Got same error :/

**Comment by imjustd** [comment]
I tried to locate the issue and can confirm when the chart uses `null` or `undefined` for the `dataKey` I got this error if we have specified `domain` for the `YAxis`.

If I remove the `domain` property form the `YAxis` I just get an empty chart with no lines.

But if I add `0` as a value the chart start to work.

**Example:**

```
<Line type="monotone" dataKey="value" />
```
- If `value` is 0 charts works even with `YAxis` with `doman` property.
- If `value` is `null` or `undefined` chart crashes.

Downgrading to recharts 1.5.0 didn't help me out, rather I made sure to always have values for the `value` in `dataKey` property.

**But I'd really like the charts to support `null`/`undefined` values too, as `0 =/= null` so if `null` or `undefined` I expect the chart to not be drawn as it worked previously, because now I need to show wrong data i.e. 0.**

I think one possible reason for this is this change:
> use _.max to replace Math.max.apply, use _.min to replace Math.min.apply

**Comment by imjustd** [comment]
Finally downgraded to v1.4.4 to make it work like before, so `null`/`undefined` values are not drawn, while other lines on the charts are displayed.

**Comment by yambakshi** [comment]
@injustd is right.
I double checked my versions and it appears the problem only occurs on v1.6.0.
Downgrading to v1.4.1 solved the problem for me.

**Comment by Eric24** [comment]
So is this fix included in 1.6.2?

**Comment by imjustd** [comment]
Yes, this is fixed, I've installed the latest and it works.

> So is this fix included in 1.6.2?

**Comment by Haschtl** [comment]
I figured out that this is still an issue, if the data-object is an empty list. Then the YAxis domain callbacks return `-infinite`, which  results in the DecimalError. I fixed it like this:
```
  <YAxis
    type="number"
    yAxisId={1}
    tickFormatter={(value: number) => {
      return value.toPrecision(4);
    }}
    domain={[
      (min: number) => {
        if (isFinite(min)) {
          return min - Math.abs(0.1 * min);
        } else {
          return 0;
        }
      },
      (max: number) => {
        if (isFinite(max)) {
          return max + Math.abs(0.1 * max);
        } else {
          return 1;
        }
      },
    ]}
  />
```

**Comment by jsDeveloper98** [comment]
> I figured out that this is still an issue, if the data-object is an empty list. Then the YAxis domain callbacks return `-infinite`, which results in the DecimalError. I fixed it like this:
> 
> ```
>   <YAxis
>     type="number"
>     yAxisId={1}
>     tickFormatter={(value: number) => {
>       return value.toPrecision(4);
>     }}
>     domain={[
>       (min: number) => {
>         if (isFinite(min)) {
>           return min - Math.abs(0.1 * min);
>         } else {
>           return 0;
>         }
>       },
>       (max: number) => {
>         if (isFinite(max)) {
>           return max + Math.abs(0.1 * max);
>         } else {
>           return 1;
>         }
>       },
>     ]}
>   />
> ```

thank you, it helps
