### ISSUE TITLE
React 16.9 - Warning: componentWillMount has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by SCasarotto** [recharts/recharts#1835]
## Do you want to request a feature or report a bug?
Reporting a bug. This should simply require a small code update if we want to leave the unsafe lifecycle methods. That something I can make a PR for but I didn't know if this would be good time to move away from these lifecycle methods all together.

## What is the current behavior?
![image](https://user-images.githubusercontent.com/13336976/62787801-1f4ef700-ba8b-11e9-8611-2e3aa40aab3d.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).
Create React Project with React@16.9 or greater and then install recharts and attempt to render a chart.

## What is the expected behavior?
No warnings.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
Recharts@1.7.0

**Comment by avindra** [comment]
`componentWillMount` and `componentWillReceiveProps` will be removed in future React. 

The maintainer is looking for contribs https://github.com/recharts/recharts/issues/1833

I'm curious if React 16 will be the supported target. If so, then we can remove /replace all the deprecated lifecycle methods.

**Comment by avindra** [comment]
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#gradual-migration-path

React 16.3 introduces the `UNSAFE_` prefix, and 17 will remove it. So, it seems like minimum support for 16.3 may be required to move forward.

**Comment by semoal** [comment]
Hi guys, I'm glad to help with this "small" code update.
We have: 14 `componentWillReceiveProps`, and just one `componentWillMount`.

`componentWillMount` could be easily fixed with a constructor initialization or possibly with `componentDidMount`(not quite sure about this)

`componentWillReceiveProps`, it's a little more complicated, we should check if they perform a side effect, in that case use `componentDidUpdate`, if not use memoization. 

- [ ] Area
- [ ] Bar
- [ ] Brush
- [ ] Line
- [ ] Scatter
- [ ] generateCategorialChart
- [ ] Sankey
- [ ] Treemap
- [ ] Text
- [ ] Funnel
- [ ] Pie
- [ ] Radar
- [ ] RadialBar
- [ ] AnimationDecorator

**Comment by damianobarbati** [comment]
@semoal actually the ideal solution in the long term is not to move to `componentDidUpdate` but to move to **hooks and effects**.

That's a clear path and future-proof approach, but I well understand that brings a lot of codebase rewrite.

**Comment by paramsinghvc** [comment]
Till the time you aren't moving recharts to hooks, at least, these unsafe methods need to be refactored, they show long warnings in the console.

**Comment by cmpaul** [comment]
I agree with @paramsinghvc , maybe do an interim fix and plan for a larger refactor in the coming major release?

**Comment by ro-savage** [comment]
@damianobarbati - Hooks aren't the only way to do things. There are still things that require lifecycle methods, and there is no current plans to depreciate the current lifecycle methods.  They are used extensively within the Facebook codebase.

Updating some/all the components to hooks may help simplify some of the components, but isn't need at all for React 17 compatibility. 

The main issue here is @xile611 is asking for maintainers (which is fine) but hasn't appointed anyone yet and isn't around to approve PRs.

**Comment by Babettestam** [comment]
Also still having the warning after updating to the latest version (1.8.3). Seems to be when using the ComposedChart.

<img width="581" alt="Screenshot 2019-10-17 at 17 25 28" src="https://user-images.githubusercontent.com/3521402/67023471-233e6b80-f103-11e9-93dd-91befd76c0ac.png">

**Comment by Chiiip** [comment]
The same is happening for me, with `recharts@1.8.5`.

![image](https://user-images.githubusercontent.com/13970946/67319214-05964b00-f4e3-11e9-9a3b-b516dbdc419c.png)

**Comment by matthewkwong2** [comment]
> I am facing the same issue, with `recharts@1.8.5`.
> 
> ![image](https://user-images.githubusercontent.com/13970946/67319214-05964b00-f4e3-11e9-9a3b-b516dbdc419c.png)

The maintainer has had tried to migrate the deprecated lifecycles to others like `componentDidUpdate` in version `1.8.0 - 1.8.2`. Yet this causes lots of unexpected behaviours since the lifecycles have different behaviours (e.g. even though it is recommended to migrate from`componentWillUpdate` to `componentDidUpdate`, they behave very differently).

The changes have ultimately reverted and a full conversion is planned but will take quite an amount of time.

**Comment by Chiiip** [comment]
Considering that changing all of these lifecycle methods it's not that easy/quick, i would suggest, for now, the addition of the `UNSAFE_` prefix to every method call. I believe it's a simpler thing to do.

That way, we get rid of the warnings with no major changes in the codebase and when React 17 is released, at least the deprecation of these methods won't be a breaking change, even though they would need to be refactored later.

**Comment by mguida22** [comment]
It looks like this was fixed in https://github.com/recharts/recharts/pull/1905 then rolled back due to  a problem supporting react@15 with the `UNSAFE_` prefix (https://github.com/recharts/recharts/commit/8ae23905ce67740b1329c42250c5e5e3de4d8744).

Is there any path forward to resolve these warnings in react@16 that is still compatible with react@15 @xile611?

I'd be happy to contribute a PR with a bit of guidance on how to best resolve this.

**Comment by amirburbea** [comment]
Can we drop support for react 15

**Comment by josephmaxim** [comment]
Still getting the warning when using ComposedChart, Line components.

**Comment by axhamre** [comment]
Perhaps reopen the issues as it's resurfaced?

**Comment by damianobarbati** [comment]
Yes, seeing this again

**Comment by mikefrancis** [comment]
It's a bit hacky and I have no idea how safe this is but this seems to be fixed in the v2 beta:

```yarn add recharts@v2.0.0-beta.1```

or

```npm install recharts@v2.0.0-beta.1```

**Comment by avindra** [comment]
@mikefrancis probably safe. we should all test and report any issues. 

the beta also fixes use of core-js 2.x (whereas `create-react-app` and other modern build tools tend to use 3.x now).

**Comment by mikefrancis** [comment]
@avindra hopefully v2 will be released soon then 🤞

**Comment by dgurneyubiqube** [comment]
Still seeing this on `2.0.0-beta.1`, and also getting a `findDOMNode` warning in dev when using `PieChart`. 

<img width="431" alt="Screenshot 2020-01-28 at 15 01 56" src="https://user-images.githubusercontent.com/58819965/73447180-1a8e4000-4356-11ea-9d96-814b373b9976.png">

In my `package.json`:
`"recharts": "^2.0.0-beta.1",`
`"babel-plugin-recharts": "^1.2.0",`

**Comment by oneillsp96** [comment]
any status updates on a stable v2 release date?
