### ISSUE TITLE
textAnchor property in Label doesn't work

### ISSUE THREAD

**Issue by Vluck** [recharts/recharts#1874]
<YAxis yAxisId="left-1" type={ytype} label={{ value: ylabel, angle: -90, position: "insideLeft", **textAnchor: "middle"** }} unit={yunit} />

the textAnchor property does not take the given value whereas it always take **start** or **end**

**Comment by xile611** [comment]
Fixed in v2.0.0-beta.3

**Comment by scrawfor** [comment]
@xile611 Should the beta have fixed all textAnchor values on label? Because I'm still seeing broken behavior in 2.0.0-beta.7.

*JSX*
```jsx
<Label postion="bottom"` and "textAnchor="left" value="My Label">
```

*HTML*
```html
<text text-anchor="middle" fill="#4b7fa6" font-weight="bold" offset="5" x="20" y="85" class="recharts-text recharts-label" >
    <tspan x="20" dy="0.71em">My Label</tspan>
</text>
```
