### ISSUE TITLE
Tooltip has a 10px white border

### ISSUE THREAD

**Issue by SeanDez** [recharts/recharts#2218]
## Do you want to request a feature or report a bug?

Bug report

## What is the current behavior?

The `<Tooltip />` component generates a thick white border.

Configuring styles for `wrapperStyle` has no effect including when `!important` is used.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/ndLhnegs/).

1. Clone https://github.com/SeanDez/callTrackVoipFrontEnd
2. Run these commands in the project root:
```
npm i && npm start
```
3. In the browser, navigate to the `/numbers` route using the nav menu

4. Hovering over the chart will show the excessively thick white border.

## What is the expected behavior?

A thin border, or none, as show in the documentation site.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

Seen in Firefox 79, Chrome 84. First time using Recharts.

```
 "dependencies": {
    "recharts": "^1.8.5"
  },
  "devDependencies": {
    "@types/recharts": "^1.8.14",
```

**Comment by xile611** [comment]
Please open an issue follow the issue guide.

**Comment by Keelando** [comment]
It seems to show up when you click on the chart. I am not able to figure out which CSS selector to use to target it because you cannot right click on the tool tip. Sometimes the white border will intermittently disappear. Quite odd

**Comment by Keelando** [comment]
Ok, this has been fixed, and the docs weren't clear to me, but if anyone else lands here from the deep reaches of the web, you want:

<Tooltip wrapperStyle={{ outline: “none” }} />

**Comment by SyoInoue** [comment]
Thank you bro....

**Comment by Codename-404** [comment]
This issue still exists, when clicking on the tooltip it has a white border and a blue outline. 
WrapperStyle doesn't work anymore
