### ISSUE TITLE
Working ref props for all components

### ISSUE THREAD

**Issue by mdrayer** [recharts/recharts#2665]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Gaining access to the component's element via ref and acting on it in some way as you would in the usual `useRef()` way. For example, if a dev wanted to get the dimensions of the `<YAxis>` component, the use of a working ref prop would make this very simple to do.

### What does the proposed API look like?
The `ref` prop already exists on components used within charts, but they do not seem to work for all components. Possibly this is an issue with the components not properly forwarding their refs? Or possibly just an oversight with leaving the ref prop exposed?

Code example:
```tsx
function MyChart() {
  const yAxisRef = useRef(null);

  useEffect(() => {
    // Access your ref and do whatever.
  }, [yAxisRef]);

  return (
    <LineChart>
      <YAxis ref={yAxisRef} />
    </LineChart>
  );
}
```
Currently, this gives us `null` for `yAxisRef.current` when we access it inside `useEffect`, whereas we would expect either the element or class for `YAxis`.

**Comment by wesoudshoorn** [comment]
Is there any update on this being implemented? 

We're trying to build some custom positioning logic for the tooltip and were looking to use a ref prop on the `<CartesianGrid />` component, but it does not seem to work.

**Comment by roger-tbg** [comment]
+1 here.  Trying to use this on ResponsiveContainer and get a deprecation warning.

**Comment by ckifer** [comment]
@roger-tbg there should only be a warning if you use ref.current.current on responsive container. That was a mistake and has been corrected backwards compatibility. The warning is just saying we'll change to the correct ref.current implementation in the next breaking release (3.0)

**Comment by roger-tbg** [comment]
@ckifer This is the relevant code:

```
const TopFiveWorkItemsGraph = ({
	data,
	xAxisLabel,
	yAxisLabel,
}: TopFiveWorkItemsGraphProps) => {
	const chartRef = useRef(null)
	const handleBarClick = (data: object) => {
		const rect = chartRef.current.getBoundingClientRect()
		setCurrentBarData({
			data,
			rect,
		})
	}
	const [currentBarData, setCurrentBarData] = useState({
		data: {},
		rect: {},
	})
	console.log('currentBarData', currentBarData)

	return (
		<ResponsiveContainer
			width="100%"
			height="100%"
			className={'rounded-lg bg-white'}
			ref={chartRef}
		>
			<BarChart
				width={500}
				height={300}
				data={data}
				margin={{
					top: 25,
					right: 30,
					left: 20,
					bottom: 15,
				}}
				onClick={handleBarClick}
			>
			```

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/blob/master/src/component/ResponsiveContainer.tsx#L75

This was done with the intent to fix the `ref.current.current` problem in a backwards compatible way while letting the user know that the old "wrong way" will be removed in the next major version. Looks like it logs no matter what when a `ref` is used which is unintentional (only should log when the incorrect `ref.current.current` is used).

Your usage is fine and isn't being deprecated, the log message just fires in both cases. Thanks for the heads up on that. 

CC @HHongSeungWoo

**Comment by ckifer** [comment]
@roger-tbg should be fixed in 2.12.2

**Comment by yuki0418** [comment]
Hi. Is there any update on this being implemented?
I try get props from ref of <CartesianGrid />, however, it seems still not working in my environment.

React: 17.0.2
recharts: 2.1.3

I try update versions but no working.

**Comment by ckifer** [comment]
No updates - it needs worked on if anyone wants to help out

**Comment by sjkcodes** [comment]
If this is implemented, it would also create a great workaround for issues like this one: https://github.com/recharts/recharts/issues/488

**Comment by ckifer** [comment]
In 3.0 you won't be able to access internal state of components via `ref`s. `ref`s will just be a reference to the eventual base element for that component. Consumers shouldn't receive internal implementation details that will change over time - this is what currently happens with `ref`s unfortunately.

We hope to expose hooks that will allow access to data (such as line points or an x,y transform) with a clean interface rather than through refs

**Comment by MichalBunkowski** [comment]
@ckifer will it allow eg. to control active dot via props? I have case where I need to sync map and chart - it is easy to read active dot and highlight corresponding point on map, but I couldn't find any solution to reverse it meaning activating dot on synced charts based on map point hover.

**Comment by luap2703** [comment]
> In 3.0 you won't be able to access internal state of components via `ref`s. `ref`s will just be a reference to the eventual base element for that component. Consumers shouldn't receive internal implementation details that will change over time - this is what currently happens with `ref`s unfortunately.
> 
> We hope to expose hooks that will allow access to data (such as line points or an x,y transform) with a clean interface rather than through refs

We just saw in the new alphas that ref on e.g. <ComposedChart /> has already been removed, but we couldn't find the newly mentioned hooks. Could you point us to it?

**Comment by ckifer** [comment]
Hi @luap2703 

I'm not sure what you mean. The latest alpha version is still a 2.x alpha version and no refs have been removed. They may however have never been there to start with. 

There is no released alpha for 3.x as we are still working on it. So tbd

**Comment by RiadHossain43** [comment]
> No updates - it needs worked on if anyone wants to help out

@ckifer i think i found something `ref.current` doesn't work probably because he chart rendering is `async`. so I tested that by adding 

```
useEffect(() => {
    const timer = setTimeout(() => {
      if (chart.current) {
        const svgElement = chart.current.querySelector("svg");
        console.log("SVG Element:", svgElement);
      }
    }, 1000); // Wait 1000ms for the chart to fully render
 
    return () => clearTimeout(timer);
  }, []);
```

after an 1000 ms i can see he chart ref is working. this looks like a work around for some use-cases. but i was wondering is there any way to make the rendering synchronous or maybe introduce some hook  to check if tthe chart has fully rendered. 

also i found that when you decrease the delay to 100ms you can a part of he chart rendered, not the full chart. Like for example within 100ms you can see the `Cartesian grid` in the following piece of code, but not the bars. bars appear if you increase the `setTimeout()` duration.

**Comment by ckifer** [comment]
You can disable animation and it should no longer be async. isAnimationActive on both Bar components
