### ISSUE TITLE
npm run build failed, problems with src/component/DefaultTooltipContent.tsx

### ISSUE THREAD

**Issue by devoldemar** [recharts/recharts#2945]
Got 3 errors as a result of npm run build. With original package-lock.json. 
The first error is
```
src/component/DefaultTooltipContent.tsx:85:14 - error TS2322: Type 'ReactNode' is not assignable to type 'TValue'.
  'TValue' could be instantiated with an arbitrary type which could be unrelated to 'ReactNode'.
    Type 'string' is not assignable to type 'TValue'.
      'string' is assignable to the constraint of type 'TValue', but 'TValue' could be instantiated with a different subtype of constraint 'ValueType'.

85             [value, name] = formatted;
                ~~~~~
```
and nexts two ones are similar:
```
src/component/DefaultTooltipContent.tsx:85:21 - error TS2322: Type 'ReactNode' is not assignable to type 'TName'.
src/component/DefaultTooltipContent.tsx:87:13 - error TS2322: Type 'string | number | boolean | {} | ReactElement<any, string | JSXElementConstructor<any>> | ReactPortal' is not assignable to type 'TValue'.
```
Also tried to upgrade @types/react from ^16.0.0 to ^18.0.0 with react itself, but it led to another similar messages.

**Comment by devoldemar** [comment]
Fixed in commit da6b9e2 "Fix typing of default tooltip formatter"

**Comment by gabgagnon** [comment]
@devoldemar The problem is still there at line 83 in DefaultTooltipContent because it can be **undefined**

Argument of type 'TValue | undefined' is not assignable to parameter of type 'TValue'.
  'TValue' could be instantiated with an arbitrary type which could be unrelated to 'TValue | undefined'.ts(2345)

```` javascript  
       let { name, value } = entry;
        if (finalFormatter) {
          const formatted = finalFormatter( TYPING ERROR --> value, name, entry, i, payload);
          if (Array.isArray(formatted)) {
            [value, name] = formatted as [TValue, TName]; 
          } else {
            value = formatted;
          }
        }
````
