### ISSUE TITLE
Recharts 2.1.15 throwing Resize Observer Error 

### ISSUE THREAD

**Issue by RajB07** [recharts/recharts#3029]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-k2xqp)

### Steps to reproduce
-

### What is expected?
Bug to be fixed soon

### What is actually happening?
Recharts 2.1.15 throwing Resize Observer Error 
  The above error occurred in the <ResizeDetector> component:      
          at ResizeDetector 
 Error: Uncaught [TypeError: _this.resizeObserver.observe is not a function]
          at reportException 

| Environment | Info |
|---|---|
| Recharts | v2.1.1 |
| React | 17 |
| System | - |
| Browser | - |

---
Jest version - 28.1.2
react testing lib version - 12.1.4

**Comment by vitalikda** [comment]
Didn't get why, but `ResizeObserver` is no longer available during jest tests. This fixed my failed test: 

```js
global.ResizeObserver = jest.fn().mockImplementation(() => {
  return {
    observe: jest.fn(),
    disconnect: jest.fn(),
    unobserve: jest.fn()
  }
})
```

**Comment by RajB07** [comment]
@vitalikda I had tried this but the test cases are still failing. It shows the same Resize Observer error.

**Comment by cjnoname** [comment]
Same error here, anyone can help?

**Comment by ckifer** [comment]
Can anyone effected by this issue give a better description of what the issue is? The CodeSanbox is not a reproduction and it is not clear weather this is an error only thrown in tests or otherwise. Thank you

**Comment by ckifer** [comment]
Closing this as this is a general known thing with `ResizeObserver`

Please refer to:
https://github.com/maslianok/react-resize-detector#testing-with-enzyme-and-jest

https://github.com/maslianok/react-resize-detector/issues/145

To resolve the issue. This is not specific to `recharts`. Thanks!

**Comment by GreenGremlin** [comment]
I'm seeing this error and the only way I've been able to fix it is to modify the recharts `ResponsiveContainer` to pass `refreshMode: 'debounce'` to `ReactResizeDetector`. I still get the error when passing a `debounce` value to `ResponsiveContainer`. I believe this is because `ReactResizeDetector` updates React state internally, so even though the callback passed to it is debounced, it still updates React state on every call. I believe the proper fix would be to forward the debounce value to `ReactResizeDetector`.

**Comment by ckifer** [comment]
@GreenGremlin can you give steps to reproduce?

**Comment by GreenGremlin** [comment]
@ckifer I've created a PR with a test that repros the root issue (debounced callbacks still updating child height and width).

https://github.com/recharts/recharts/pull/3175

**Comment by ckifer** [comment]
Should be fixed in 2.4.0

**Comment by khuynhepi** [comment]
Hi, I am still getting the same error even with 2.8.0.  can anyone help?

**Comment by ckifer** [comment]
ResizeLoop observer errors are benign and won't cause you any issues https://stackoverflow.com/a/50387233/8050147

Are you getting it consistently? If so can you provide a reproduction?

**Comment by floccini** [comment]
Had the same problem today, currently using recharts on 2.10.3:

![image](https://github.com/recharts/recharts/assets/55555174/c86750e2-b6b3-4e59-af5a-da82202b7937)

After adding the mock implementation on ResizeObserver as suggested by @vitalikda fixed the issue.

**Comment by ckifer** [comment]
Yep, makes sense. It will generally have to be mocked in tests no matter where it is used
