### ISSUE TITLE
`angle` prop on XAxis is not considered when deciding which ticks to show

### ISSUE THREAD

**Issue by petii** [recharts/recharts#3468]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-hji7ig?file=/src/index.js)

### Steps to reproduce
1. Create a chart which does not have enough space for all X axis ticks to be shown
2. Rotate X axis tick labels through the usage of the `angle` prop

### What is expected?
More ticks are shown if they are able to be rendered without overlap.

### What is actually happening?
The same ticks are rendered as if they were not rotated.

| Environment | Info |
|---|---|
| Recharts | v2.3.0 |
| React | 16.8.6 |
| System | N/A |
| Browser | N/A |

---
The methods in `src/cartesian/getTicks.ts` are all under the impression that the text is displayed horizontally, because _getStringSize_ in `src/util/DOMUtils.ts` only considers the font styling and not the transformations.

This is a tricky thing to consider however, as with non right angles, the rotated SVG elements could be allowed to overlap, so the _getBoundingClientRect_ call in _getStringSize_ is probably not sufficient.

**Comment by ckifer** [comment]
+1 to the tricky nature of this. Also hard to test (thank you Storybook for interaction tests/running in the browser).

Totally on board

**Comment by Sergiiivzhenko** [comment]
workaround for me was to set interval={0}

**Comment by petii** [comment]
> workaround for me was to set interval={0}

@Sergiiivzhenko While that usually works, if you have many ticks (or a small chart) that can lead to the ticks being rendered on top of each other.

**Comment by bernardobelchior** [comment]
I have been facing this problem at work, so I've implemented a fix [here](https://github.com/recharts/recharts/pull/3576).

**Comment by ckifer** [comment]
released in 2.7, resolving this

**Comment by moaazbhnas228** [comment]
This is still an issue in version `2.15.1`.

``` js
              <XAxis
                dataKey="step_description"
                tickLine={false}
                tickMargin={0}
                axisLine={true}
                interval={0}

                
                angle={45}
                tick={{ dy: 20 }}
                // tickSize={2}
              />
```

![Image](https://github.com/user-attachments/assets/fced2a14-760b-4aad-9744-78804e131904)

**Comment by ckifer** [comment]
Hey @moaazbhnas228 i don't think this issue describes the same thing you are experiencing. Previous to this change, ticks were actually hidden (could see no text) because they were being calculated as if they were horizontal still. 

In your screenshot it looks like the text is getting cut off because there is not enough room in the SVG. Currently, there is no auto-adjustment of chart margin based on if your ticks are being cut off or not as this is rather expensive to check against. 

For now you can add more margin bottom on the chart. But this would be good as a new feature request if there isnt already one

**Comment by moaazbhnas228** [comment]
Thank you @ckifer 

![Image](https://github.com/user-attachments/assets/f1e3fbe1-2663-43c6-88c6-f73a1fea6d0a)

The text started appearing after I added the margin. Only issue now is the alignment. I didn't find `tickAlign` implemented.
Should I add a new feature request?

**Comment by ckifer** [comment]
It's an SVg property. Try `tick={{ tickAlign: "start" }}`

**Comment by moaazbhnas228** [comment]
Thank you, @ckifer 
It's actually `textAnchor`

**Comment by ckifer** [comment]
ah sorry I was going off of memory
