### ISSUE TITLE
Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead. at {Component}

### ISSUE THREAD

**Issue by marco-digennaro** [recharts/recharts#3615]
Using a library that include recharts v2.6.2 i get the following error in the console.

> Curve: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead. at Curve

the charts are rendered normally thou.

**Comment by ckifer** [comment]
Thanks, noted! Unfortunately moving away from defaultProps causes unintended bugs due to the way recharts works. But this is known and we're trying to get away from them where we can.

**Comment by cdimitroulas** [comment]
FYI this also happens for the Tooltip component

**Comment by ckifer** [comment]
Reference for why this is an issue https://github.com/recharts/recharts/issues/3438#issuecomment-1467419256

**Comment by ckifer** [comment]
@akamfoad all of our functional refactors are going to have this issue. We may have to prepared to handle soon as I'm going to release 2.7. Let me know if you have any thoughts

**Comment by akamfoad** [comment]
@ckifer 
I was always feeling bad about the defaultProps but in my refactors I kept them just in case and to reduce the number of changes.

But I think the sooner we embrace JS default params the better, I see many teams are going in this direction, especially those who use TypeScript, I see that is quite the default practice.

This is not going to break semver if we do it in v2, because we just change how we receive the default values, internally, for the users of the library everything will be the same and the warning goes away. What do you think?

**Comment by ckifer** [comment]
@akamfoad I totally agree, but we still have the cloneElement issue linked above (https://github.com/recharts/recharts/issues/3438#issuecomment-1467419256).

I believe all of the components we have refactored besides Tooltip are safe from that issue so we should be able to move them over

**Comment by ckifer** [comment]
I believe [this list ](https://github.com/recharts/recharts/blob/4ee4124f3d73f9487b4b74d6aedac0f87af8d3a2/src/chart/generateCategoricalChart.tsx#L2161-L2182) holds those that we cannot touch without fear of breaking things

**Comment by akamfoad** [comment]
So only those components will cause issue if defaultProps is removed, that another component/function needs to access them, including `cloneElement`, before the component is initialized.

I'm guessing there is a lot of them, especially those from the list in `generateCategoricalChart`.

Which means they in fact cause breaking change, when migrated to default params. So we might need to hold off here and revert the Tooltip refactor, that is an easy one.

The warning is shown only for Functional Components with defaultProps, but the default behavior may changes in the future for how this affects components (if I understood the RFC correctly). Which means, its probably for the best to prepare for v3.

**Comment by akamfoad** [comment]
Btw @ckifer 

I think its probably for the best, this might encourage us to have  major version (not very soon tho), where we internally do not rely on defaultProps, or cloneElement, instead we use normal JS default params, and renderProps (which is not my personal favorite), or Context API.

This way, the children can both render and subscribe to context's provided by the charts (or a an HoC) parent and render, clutter-free

**Comment by ckifer** [comment]
Thanks for the thoughts @akamfoad! Yeah I agree - I've been shying away from 3.x because it's a lot of work and there's a lot of breaking changes we need to merge in and document but there hasn't really been any meaningful progress made towards it. 

But yes we definitely need to 100% rid ourselves of the cloneElement approach, it's the cause of a lot of issues (but it's also some of the magic of recharts which is why it's tough to remove or at least tough to test once you remove it).

**Comment by jocarrd** [comment]
![image](https://github.com/recharts/recharts/assets/55456507/0e8b7329-6685-4c74-8451-fcbafe1a369f)
Same problem...

**Comment by ckifer** [comment]
No solution yet but we're aware of it, thanks

**Comment by shohan-pherones** [comment]
I also need the solution asap, do your job devs.

**Comment by ckifer** [comment]
There are no devs that work on this project as a job

**Comment by zwhitchcox** [comment]
Just leaving this here:

```ts
const error = console.error;
console.error = (...args: any) => {
  if (/defaultProps/.test(args[0])) return;
  error(...args);
};
```

**Comment by ooanishoo** [comment]
> zwhitchcox

Hi, is this a temporary fix that we can implement for now?

**Comment by zwhitchcox** [comment]
@ooanishoo This will just hide the warning, but there's not really anything else you can do until it's fixed upstream anyway.

**Comment by wuahi** [comment]
Having the same issue. Is there an update on where this might be fixed?

**Comment by evanlong0926** [comment]
I was just about to ask a question, but I guess I won't. Everyone knows 🤣

**Comment by ckifer** [comment]
No update really besides some noodling in my head to try to pick a path forwards. If I work on anything at all next it will be this, I just can't make time for it right now as other priorities prevail.

**Comment by ckifer** [comment]
Risky elements are defined (by me at least 😅 ) as any that are referenced by a call to `findAllByType` `findChildByType` and those in the `map` in `generateCategoricalChart` (see issue linked above - https://github.com/recharts/recharts/issues/3438#issuecomment-1467419256). This comes out to:

1. Cell
2. Brush
3. Tooltip
4. Legend
5. ErrorBar
6. XAxis
7. YAxis
8. ZAxis
9. PolarAngleAxis
10. PolarRadialAxis
11. Radial
12. Label
13. LabelList
14. ReferenceDot
15. ReferenceLine
16. ReferenceArea
17. CartesianGrid
18. PolarGrid
19. Customized
20. Any graphical child - Bar, Area, Line, Scatter, Funnel, Pie, Radar, RadialBar


All other components outside of these should be able to be refactored to use default params with relative certainty they won't break things. This makes this issue actionable and means that `Text`, `Curve` and any others not on this list can be moved over any time. @nikolasrieble @akamfoad for vis.

If anyone wants to take the changes or the change for one component let me know.

**Comment by ckifer** [comment]
Text refactored in #3670. Curve is open for contribution as well as any others that may currently have issue

**Comment by ckifer** [comment]
`Tooltip` is one of the affected components that gets funky. `findChildByType` is called for Tooltip multiple times in different places. Some use props that don't have a default set, others do. 

Safe references:
- https://github.com/recharts/recharts/blob/38253c9806aab8099c2182297a90f7e04706205f/src/chart/Treemap.tsx#L359-L361 - only checking for existence in react tree
- https://github.com/recharts/recharts/blob/38253c9806aab8099c2182297a90f7e04706205f/src/chart/Treemap.tsx#L381-L383 - existence check
- https://github.com/recharts/recharts/blob/38253c9806aab8099c2182297a90f7e04706205f/src/chart/generateCategoricalChart.tsx#L1214 - reference to `shared` prop which is not defined in defaultProps

Unsafe references:
- https://github.com/recharts/recharts/blob/38253c9806aab8099c2182297a90f7e04706205f/src/chart/Sankey.tsx#L466-L484 - use of `trigger` which is set in default props
- https://github.com/recharts/recharts/blob/38253c9806aab8099c2182297a90f7e04706205f/src/chart/generateCategoricalChart.tsx#L1352-L1356 - reference to `trigger` which is set in defaultProps. This one wouldn't break though as the value its referencing is not the default
- https://github.com/recharts/recharts/blob/38253c9806aab8099c2182297a90f7e04706205f/src/chart/generateCategoricalChart.tsx#L2055 - reference to existence as well as `trigger` (but same as above, not a check for the default value)
- https://github.com/recharts/recharts/blob/38253c9806aab8099c2182297a90f7e04706205f/src/chart/Sankey.tsx#L489-L494 - reference to trigger
- https://github.com/recharts/recharts/blob/38253c9806aab8099c2182297a90f7e04706205f/src/chart/Sankey.tsx#L512-L514 - reference to trigger
- 

Unsure:
- https://github.com/recharts/recharts/blob/38253c9806aab8099c2182297a90f7e04706205f/src/chart/generateCategoricalChart.tsx#L1931-L1945 - this one calls `React.cloneElement` on the found Tooltip with some new props... I'm not sure if react merges these with defaultProps or not (I think shallow merge?), I would assume so and therefore unsafe 
- https://github.com/recharts/recharts/blob/38253c9806aab8099c2182297a90f7e04706205f/src/chart/Treemap.tsx#L672 - same as above

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/pull/3671 fixes `Curve`

Tooltip... is still an issue as seen above. Please yell out any other components that throw the error

**Comment by ckifer** [comment]
https://github.com/recharts/recharts/pull/3681 fixes `Trapezoid` and `Symbols`

This is about the speed I can go right now with some spurts here and there, open to contributions as always 🙏🏼

**Comment by akamfoad** [comment]
#3685 fixes `Cross`
#3686 fixes `Rectangle`

**Comment by ckifer** [comment]
All of the easy components have been refactored to safely use default params - this leaves `Tooltip`, `Label`, `LabelList` without a great solution. 

we can
1. revert back to classes - not preferred
2. store a map of default params to component type and merge user params with default params where `findByType` is used - semi-hacky and 1000% temporary but probably preferred

**Comment by akamfoad** [comment]
Wouldn't `2` make maintenance even more complicated?

**Comment by ckifer** [comment]
Yeah I guess it depends on how we did it. Maybe it's worth just reverting back to classes until the macro problem is addressed

**Comment by akamfoad** [comment]
Initially this effort was to make the implementation simpler so we can easily do changes, but if this makes it more complex I'd say reverting them is the better option now.

**Comment by ckifer** [comment]
yeah, as much as I hate to do that I agree. we have the refactors in git history to go back to so it isn't like they are much effort

**Comment by nikolasrieble** [comment]
Good call @akamfoad! Thank you. I believe we must focus our effort on the large problems. 
Lets revert the initial refactoring instead of further adding complexity. Lets come up with an attack plan for `generateCategoricalChart` 😅

**Comment by akamfoad** [comment]
A while back I put some efforts into that, the result was pathetic, it fights back hard😅

You can see my progress here: https://github.com/akamfoad/recharts/tree/akamfoad/migrate-generateCategoricalChart

**Comment by nikolasrieble** [comment]
@akamfoad I believe we should first refactor the component - extract unit testable functions and add unit tests. The function must be as small as possible, and only a high level combination of calls to smaller - tested - helpers. Only then can we reasonably refactor.

**Comment by akamfoad** [comment]
@nikolasrieble that is definitely a better approach, I did bite the whole thing at once😂

I'm gonna take another look soon.

**Comment by ckifer** [comment]
I was thinking at looking at React Router and how they prevent certain components from being rendered and within others (Route can't be rendered outside of Routes). I know maybe eventually we want to rid ourselves of that type of setup, but it might be worth a peruse to get this same type of functionality

**Comment by ckifer** [comment]
`Label` and `LabelList` have always been functions :/ - this leaves us to revert Tooltip, but idk if I really want to re-write Label and LabelList as a class...

**Comment by evanlong0926** [comment]
Refactor it using [radix-ui](https://www.radix-ui.com/). 🤗

**Comment by ckifer** [comment]
> Refactor it using [radix-ui](https://www.radix-ui.com/). 🤗

@evanlong0926 that seems pretty unrelated 😅 



Either way @akamfoad @nikolasrieble `Label` and `LabelList` seem safe to me - they do not directly reference props after `findAllByType`, `findChildByType` - they call `cloneElement` which correctly invokes the component and causes default params to be set.

See [here](https://github.com/recharts/recharts/blob/master/src/component/Label.tsx#L524-L535) and [here](https://github.com/recharts/recharts/blob/master/src/component/LabelList.tsx#L105-L118)

**Comment by ckifer** [comment]
These should all be resolved in 2.8.0. Please help me check/bug bash. Thank you all for your patience <3

**Comment by ckifer** [comment]
Going to close this for now, will re-open if there are any issues

**Comment by alex-grover** [comment]
I'm still seeing this error logged for `ReferenceDot` in 2.8.0. With a quick search, it looks like `defaultProps` is also still used in `X/Y/ZAxis`, `ReferenceLine/Area`, and `ErrorBar`.

**Comment by ckifer** [comment]
Oof, these ones were like this previous to us beginning to refactor components to functions and have a lot of sketchy references that will break if we remove them like this one https://github.com/recharts/recharts/blob/16f66c3ff656d02524aa8c31b1f2d35b15be94f5/src/util/ChartUtils.ts#L1179-L1185

Definitely more hesitant to take action on the axes but the `Reference` components and `ErrorBar` should be able to be refactored safely...

@alex-grover does the error get logged if you use `X/Y/ZAxis`?

I still can't reproduce these errors so it is tough to test - if anyone can get them to log in a sandbox that would be incredible

**Comment by alex-grover** [comment]
I'm not seeing the error logged with the Axis components.

Had some issues getting a sandbox set up, but this minimal example produces the error for me in case that works for you: https://github.com/alex-grover/recharts-default-props-console-error

**Comment by ckifer** [comment]
Thank you!

**Comment by JacobWeisenburger** [comment]
`Warning: ReferenceLine: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

I'm still having this problem on recharts: 2.10.3

any workarounds?

**Comment by jocarrd** [comment]
@JacobWeisenburger same error

**Comment by ckifer** [comment]
Heard that this is still an issue. These ones weren't priority as they have been this way for some time and the other components were not. This issue will remain open until ReferenceLine, ReferenceArea, ReferenceDot are refactored

**Comment by ckifer** [comment]
@PavelVanecek  we're not using default props anymore in the axes correct?

**Comment by guillerp8** [comment]
Same here using 2.11.0 in xAxis

**Comment by PavelVanecek** [comment]
We're working towards removing defaultProps but for now, all axes still use them.

**Comment by Feli87** [comment]
> Just leaving this here:
> 
> ```ts
> const error = console.error;
> console.error = (...args: any) => {
>   if (/defaultProps/.test(args[0])) return;
>   error(...args);
> };
> ```

Tnks!

**Comment by SebastianNarvaez11** [comment]
![image](https://github.com/recharts/recharts/assets/48743216/16d8e3ea-5d56-4a4d-bab3-f5e9c846817c)
![image](https://github.com/recharts/recharts/assets/48743216/17054156-c886-4433-a3f2-de67a1027c3e)
Same problem here

**Comment by ckifer** [comment]
See above comments, this is known. 

Refactoring these is not as simple as moving defaultProps to default parameters. Legacy recharts code references props from these components before the components are initialized. Where defaultProps exist before a component is initialized, default params do not. Changing this only to get rid of this warning will result in more bugs than it fixes, we're working on refactoring some of the magic away (and understanding things better ourselves) so we can remove defaultProps safely.

**Comment by kornjiradej** [comment]
> > Just leaving this here:
> > ```ts
> > const error = console.error;
> > console.error = (...args: any) => {
> >   if (/defaultProps/.test(args[0])) return;
> >   error(...args);
> > };
> > ```
> 
> Tnks!

Where to place this code??

**Comment by troneras** [comment]
> > > Just leaving this here:
> > > ```ts
> > > const error = console.error;
> > > console.error = (...args: any) => {
> > >   if (/defaultProps/.test(args[0])) return;
> > >   error(...args);
> > > };
> > > ```
> > 
> > 
> > Tnks!
> 
> Where to place this code??

If you are using Next14, in any client ("use client") component does the trick. Just remember to leave a comment for your future you for wtf is that:

```ts
// Override console.error
// This is a hack to suppress the warning about missing defaultProps in recharts library as of version 2.12
// @link https://github.com/recharts/recharts/issues/3615
const error = console.error;
console.error = (...args: any) => {
  if (/defaultProps/.test(args[0])) return;
  error(...args);
};
```

**Comment by benyamynbrkyc** [comment]
> > > > Just leaving this here:
> > > > ```ts
> > > > const error = console.error;
> > > > console.error = (...args: any) => {
> > > >   if (/defaultProps/.test(args[0])) return;
> > > >   error(...args);
> > > > };
> > > > ```
> > > 
> > > 
> > > Tnks!
> > 
> > 
> > Where to place this code??
> 
> If you are using Next14, in any client ("use client") component does the trick. Just remember to leave a comment for your future you for wtf is that:
> 
> ```ts
> // Override console.error
> // This is a hack to suppress the warning about missing defaultProps in recharts library as of version 2.12
> // @link https://github.com/recharts/recharts/issues/3615
> const error = console.error;
> console.error = (...args: any) => {
>   if (/defaultProps/.test(args[0])) return;
>   error(...args);
> };
> 
> export function SomeComponent....
> ```

Here's a simple component you can place anywhere in the project in order to turn off the warning inspired by the earlier comments.

```
"use client";

export const TurnOffDefaultPropsWarning = () => {
  // Override console.error
  // This is a hack to suppress the warning about missing defaultProps in the recharts library
  // @link https://github.com/recharts/recharts/issues/3615
  const error = console.error;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  console.error = (...args: any) => {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
    if (/defaultProps/.test(args[0])) return;
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    error(...args);
  };

  return <div className="absolute h-0 w-0"></div>;
};
```

**Comment by trevoruptain** [comment]
> Here's a simple component you can place anywhere in the project in order to turn off the warning. Inspired by the earlier comments.
> 
> ```ts
> "use client";
> 
> export const TurnOffDefaultPropsWarning = () => {
>   // Override console.error
>   // This is a hack to suppress the warning about missing defaultProps in the recharts library
>   // @link https://github.com/recharts/recharts/issues/3615
>   const error = console.error;
> 
>   // eslint-disable-next-line @typescript-eslint/no-explicit-any
>   console.error = (...args: any) => {
>     // eslint-disable-next-line @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
>     if (/defaultProps/.test(args[0])) return;
>     // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
>     error(...args);
>   };
> 
>   return <div className="absolute h-0 w-0"></div>;
> };
> ```

Thanks, @benyamynbrkyc, for the hack to suppress defaultProps warnings. It's helpful but complicates debugging by masking the origins of other errors. Here's a tweaked version aiming to keep stack traces clear:

```ts
"use client"

import React, { useEffect } from 'react';

export const TurnOffDefaultPropsWarning: React.FC = () => {
  useEffect(() => {
    const originalConsoleError = console.error;

    console.error = (...args: any[]) => {
      if (typeof args[0] === 'string' && /defaultProps/.test(args[0])) {
        return; // Suppress the warning by not calling the original console.error
      }

      originalConsoleError(...args);
    };

    return () => {
      console.error = originalConsoleError;
    };
  }, []);

  return null;
};
```

**Comment by trancethehuman** [comment]
Hope the team is still actively working on fixing this on Axis 🔥

**Comment by ckifer** [comment]
@trancethehuman the (currently ~2 active people) team are individuals that work on the project in their spare time only so please bare with us 🙏🏼. Contributions as always are appreciated and encouraged if you'd like something pushed through faster

**Comment by trancethehuman** [comment]
@ckifer let me know if I can help test

**Comment by ckifer** [comment]
@trancethehuman sure, we'll make some alpha releases as we start to address issues like this one

**Comment by mauserez** [comment]
How to ignore this warning in Next JS Project ?

**Comment by kirkouimet** [comment]
Recharts is fantastic, glad this issue is tracked. Sending love to anyone who will work on this one :)

**Comment by Hayydenn09** [comment]
i also have a question, the team have working to resolve this issue or not? because i have same issue right now @ckifer

**Comment by ckifer** [comment]
@Hayydenn09 see posts above, not yet but we're working on it

**Comment by scottykaye** [comment]
Our team sees this issue in 2.8.0

Just to recap this 🧵
- A solution is being worked on, keep an eye out for it.
- End users can scrub the console logs in a client component if need be as suggested [here](https://github.com/recharts/recharts/issues/3615#issuecomment-1947814453).

**Comment by darincon** [comment]
> i also have a question, the team have working to resolve this issue or not? because i have same issue right now @ckifer

@Hayydenn09 I also have a question, do you understand that this is maintained by the community? Because if you do then feel free to contribute instead of demanding volunteers to fix this.

@ckifer thanks for keeping us all up to date and for taking a look at this issue. You people rock!

**Comment by tanjunior** [comment]
The amount of unappreciative people is absurd. Thank you for all the contributors working on this project.

**Comment by taylorjdawson** [comment]
> Hiding the error doesn't solve it. Please stop suggesting it.

There are 100% valid reason for adding this:
If you're publishing a site it looks sloppy/signals a bad product to see errors in the console, it is a warning that is getting thrown as an error which is also inappropriate, and there's no clean way to suppress the "error" (warning) – for instance `suppressHydrationWarning` in Next.js. Therefore your options are: Launch a site that might seem "buggy" or add this error suppression and then wait for the devs to fix. I'd choose the later.
Its imperative to allow devs to make that decision for themselves and avoid [absolute statements](https://www.youtube.com/watch?v=kVu_yMEhUfM). Its about learning and growing together as a community. ❤️

**Comment by rahul8864** [comment]
![image](https://github.com/recharts/recharts/assets/74202040/3b492495-7f68-4d16-b9e9-379b2c54af77)

I noticed the warning message only appears locally and not in production.

**Comment by PaulSinghDev** [comment]
@ckifer I'm happy to help try and solve this/implement some fixes. I've had a read through the comments here and understand the issue is related to the order in which props/args are processed. 

I'm presuming this is an issue as the digesting components need to access the props prior to the component being rendered in order for them to be able to do some work with the props. If that is the case and you already have an idea of where the change needs to be made I'd be happy to take a stab at it if you point me in the right direction :)

**Comment by ckifer** [comment]
@PaulSinghDev feel free to give it a shot on the 3.x branch! I can't confirm but we may have gotten enough refactoring done to unblock this. 

Essentially, recharts did a ton of reading React elements from the render tree, manipulating them, and cloning them. During the cloning process it also gets props directly from the elements it reads. This was/is problematic in many ways, but especially in the case of defaultParams when the defaults do not exist until the component has actually been called yes.

**Comment by PaulSinghDev** [comment]
@ckifer perfect! Thanks for explaining, it definitely helps me understand the issue/what needs to be done. I will try and get something whipped up over this weekend n let you know if there is anything I may be unclear on :)

**Comment by LUCKY-JANGIR** [comment]
sorry Mr😅,but i am here through the google search results so basically my point is that about what all if talking-NextJs or ReactJs.
because the same problem i faced is while working with ReactJs .
and my Question is that- is the conclusion is that there is no solution for this problem till now?

and as @kornjiradej suggested to hide this problem with a simple function , if i do so is that means i face no problem while working and publishing the app

**Comment by ckifer** [comment]
No solution yet, working on it as stated above

**Comment by ChengHauLow** [comment]
What i do is like normal javascript function, for example:

function Header({text='No More Waiting'}) {
  return (
    <header>
        <div className="container">
            <h2>FeedBack UI - {text}</h2>
        </div>
    </header>
  )
}


export default Header

import Header from './components/Header';

function App() {
  return (
    <>
      <Header  text="No more hello world"/>
      <Header />
      <div className="container">
        <h1>My App</h1>
      </div>
    </>
  );
}

export default App;


This work exactly like defaultProps, so it is the way we should do in the next major update?

**Comment by ckifer** [comment]
Yep, that's how we'll do it most likely. As mentioned above, it's a bit more complicated than that though which is why large amounts of refactoring need done first

**Comment by Danielvandervelden** [comment]
Thanks for working on this you guys. Patiently waiting for the eventual fix 🙏

**Comment by PaulSinghDev** [comment]
@ckifer just wanted to let you know I didn't forget last weekend, I crashed my bicycle (whoops) so wasn't in much of a space to bang it out. I'll have time this weekend to have a look :)

**Comment by PaulSinghDev** [comment]
@ckifer Just been going through this this morning and noticed it seems as though we have an `XAxisContext` which is responsible for generating a prop map which is fed to `useXAxisOrThrow` -- from my understanding this hook is returning the current props for the axis to the `XAxis` component and the returned value is being fed to the `CatesianGrid` component. 

With all that being said, would a sufficient solution be to update the context or hooks to implement a default props of some sorts? I have had a go at implementing a solution but I think I most likely need a bit of a more detailed mental modal of how the overall parts are playing together as my initial attempt killed the unit tests 👀

**Comment by PavelVanecek** [comment]
That's correct. The problem is that there are parts of code that read
defaultProps directly from DOM, by searching the element tree and then
matching displayName.

Once those are removed, and the context and hooks is the way to do that,
the warning will go away.

**Comment by ckifer** [comment]
+1, its basically all going to lead back to untangling `getAxisMapByAxes` which is going to be a relatively large undertaking. I for example, tried to refactor ReferenceLine to use defaultParams, but I can't because then axis generation does not know that my reference line has a `yAxisId` of 0 and an `xAxisId` of 0, and then can't act on axis domain in the case that `ifOverflow="extendDomain"` for example (the domain is supposed to get value added to it if the reference line is outside of the default domain).

We need to make the connection between reference elements and axis elements in a different way (context and hooks)

**Comment by zeroliu** [comment]
Thanks for keeping us posted for the progress @ckifer ! Really appreciate it!

I found this thread when testing react 19 beta. Looks like this starts to cause runtime issues in React 19 since `defaultProps` is removed. https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops

**Comment by ckifer** [comment]
Sure thing!

Right, this is why the warning is logged. We won't be able to support React 19 until we finish this. 

Although in 2.x branch we might accept #4542 as version 2.12.8 which would move these components back to classes to get rid of the errors. We could then add react 19 to peerDeps and keep working on 3.x without blocking people from upgrading.

**Comment by jukkahuuskonen** [comment]
> That's correct. The problem is that there are parts of code that read defaultProps directly from DOM, by searching the element tree and then matching displayName. Once those are removed, and the context and hooks is the way to do that, the warning will go away.
> […](#)

Could this be taken care of (atleast while waiting for next version) by using a wrapper function, that would get the defaultValues from DOM and either pass props or if they are missing then the defaultValues to the real component?

```
const RealComponent = (param1, param2) => {
  ...
};

const Wrapper = ({ param1, param2 }) => {
  const defaultValues = useMemo(
    () => ({ param1: getParamFromDom('defParam1'), param2: getParamFromDom('defParam2') }),
    []
  );
  return <RealComponent param1={param1 || defaultValues.param1} param2={param2 || defaultValues.param2 } />;
};

```

or did I totally misunderstand the problem...

**Comment by ckifer** [comment]
@jukkahuuskonen I guess when we say dom here we're talking about from react elements, or the virtual dom. The linked PR wraps our current functions in class components which solves the issue. I think that the path forward while waiting

**Comment by h0lme3** [comment]
Thanks for your work @ckifer ! Will be waiting for your great updates!

**Comment by gabrielkuslansky** [comment]
@ckifer Thank you for your efforts!

**Comment by GabeKuslansky** [comment]
@ckifer Thank you for your efforts!

**Comment by diogotrindadeversion1** [comment]
Removing defaultProps do not make any sense by the React team.
defaultProps have been a standard on the documentation for years, always on the main examples. And it helps organizing the code with less nested objects. I believe that is a better solution of nesting things with JavaScript.
Lots of libraries will have the same issue, including custom private libraries of components, that does not make sense to refactor everything, just because yes.

So I think that you should one an issues on the React repository.
They have a new compiler, they should use it for optimization, and keep defaultProps alone/working.

**Comment by PavelVanecek** [comment]
defaultProps will stay on class components. This warning is about defaultProps on functional components.

So we could technically solve this by rewriting everything from functional components to classes. But that also means rewriting all hooks.

**Comment by diogotrindadeversion1** [comment]
> defaultProps will stay on class components. This warning is about defaultProps on functional components.
> 
> So we could technically solve this by rewriting everything from functional components to classes. But that also means rewriting all hooks.

That does not make any sense. Using classes is going back in time, and it is an old pattern. We can have functions with defaultProps. 
Everybody should have that conversation on the React repository.

**Comment by ckifer** [comment]
Alpha release - https://www.npmjs.com/package/recharts/v/2.13.0-alpha.0
This BREAKS things in R19 (though they're already broken), shouldn't in R18

Please use this alpha to see if defaultProps warnings are gone (and make sure things are still working as normal in R18 and below). For now, all the function components with issues have been wrapped with classes

**Comment by ckifer** [comment]
Nice! All credit to @eps1lon for the interim solution. 

Work still needed for things not to break in R19 so I'll wait for more feedback and see if we can get full support in before resolving this. Thanks everyone.

**Comment by ckifer** [comment]
https://www.npmjs.com/package/recharts/v/2.13.0-alpha.1
Should have more R19 support if not all of it (minus the need to disregard peerDeps and install react-is@19)

Please test this one as well on all React versions 16.8-19 to see if anyone runs into issues. Thanks! 🚀

**Comment by MD-YeakubNabi-Hridoy** [comment]
Warning: XAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
how to fix this

**Comment by ckifer** [comment]
Try installing the alpha version listed above

**Comment by Wallauerr** [comment]
@ckifer it worked! 
The console error is gone.

**Comment by barhouum7** [comment]
Hey y'all, I think installing `v2.10.2` should fix the warning, so try this:

`npm install recharts@2.10.2`

**Comment by marcusvinicius0** [comment]
Console error is gone, thx a lot for the support!

**Comment by ckifer** [comment]
I'm going to close this since we have a path forwards to remove the errors

Solution is `npm i recharts@alpha`
I will post back here again when R19 is out and I can release `2.13.0`, that will contain the alpha fixes.

Feel free to continue to report any issues found here (or R19 related [here](https://github.com/recharts/recharts/issues/4558))

Thanks all

**Comment by jewseppi** [comment]
after installing the alpha version, i started getting an error on my build server about a missing dependency (ajv). had to add the library to package.json to resolve.

**Comment by jewseppi** [comment]
I'm also seeing this:

ERROR in ./node_modules/recharts/es6/index.js
Module build failed (from ./node_modules/source-map-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, open 'C:\DevOps\RetailServices.Web\ret
ailservices.web.management\node_modules\recharts\es6\index.js'

**Comment by ckifer** [comment]
Thanks

`npm ls ajv` in recharts results in

```
recharts % npm ls ajv
recharts@2.13.0-alpha.4 /Volumes/workplace/recharts
├─┬ @storybook/react-webpack5@8.1.2
│ └─┬ @storybook/builder-webpack5@8.1.2
│   └─┬ webpack-dev-middleware@6.1.3
│     └─┬ schema-utils@4.2.0
│       ├─┬ ajv-keywords@5.1.0
│       │ └── ajv@8.13.0 deduped
│       └── ajv@8.13.0
├─┬ babel-loader@9.1.3
│ └─┬ schema-utils@4.2.0
│   ├─┬ ajv-formats@2.1.1
│   │ └── ajv@8.12.0
│   ├─┬ ajv-keywords@5.1.0
│   │ └── ajv@8.12.0 deduped
│   └── ajv@8.12.0
├─┬ eslint@7.32.0
│ ├─┬ @eslint/eslintrc@0.4.3
│ │ └── ajv@6.12.6 deduped
│ ├── ajv@6.12.6
│ └─┬ table@6.8.1
│   └── ajv@8.12.0
├─┬ terser-webpack-plugin@5.3.10
│ └─┬ schema-utils@3.3.0
│   ├─┬ ajv-keywords@3.5.2
│   │ └── ajv@6.12.6 deduped
│   └── ajv@6.12.6 deduped
└─┬ webpack-dev-server@4.15.1
  ├─┬ schema-utils@4.0.0
  │ ├─┬ ajv-keywords@5.1.0
  │ │ └── ajv@8.12.0 deduped
  │ └── ajv@8.12.0
  └─┬ webpack-dev-middleware@5.3.3
    └─┬ schema-utils@4.0.0
      ├─┬ ajv-keywords@5.1.0
      │ └── ajv@8.12.0 deduped
      └── ajv@8.12.0
```

So I don't think this is on the recharts side of things, everything listed there are devDependencies

**Comment by JJozef** [comment]
The "recharts" version: "`2.13.0-alpha.1`", not a single problem (with nextjs 14).

**Comment by ckifer** [comment]
@JJozef there are some bugs if you upgrade to React 19, but glad to hear no regressions otherwise. The latest alpha should be good in R19 (at least no issues thus far).

@jewseppi I can `npm i recharts@alpha` and see the `node_modules\recharts\es6\index.js` exists. Not sure why its being weird for you
![image](https://github.com/recharts/recharts/assets/25180830/d4a652ef-fb3f-47c8-b9e3-eb2d6e4e65b8)

**Comment by jewseppi** [comment]
Okay thanks for the quick response.

**Comment by ElhadjBoubacar** [comment]
Android Bundled 6042ms C:\Users\MON P C\Desktop\Rappelle\mon-app\node_modules\expo\AppEntry.js (1051 modules)
 ERROR  Warning: Unknown: Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.
    in RCTView (created by View)
    in View (created by Rendez)
    in RCTView (created by View)
    in View (created by Rendez)
    in RCTView (created by View)
    in View (created by Rendez)
    in RCTView (created by View)
    in View (created by Rendez)
    in Rendez (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous) (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)

**Comment by ckifer** [comment]
@ElhadjBoubacar please upgrade to the alpha version if you want the warning to go away. Will release 2.13 when R19 is released

**Comment by Yumat10** [comment]
This is awesome, thank you all for the hard work!! 🙌

**Comment by CodingReaper1** [comment]
i tried downloading alpha but it didnt work console error didnt go away  Warning: XAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

**Comment by ckifer** [comment]
There's only one implementation, so there can't be some people that this is fixed for and others that it isn't. Please `npm ls recharts` (or equivalent) and make sure you're using the alpha version

**Comment by wDeanSharon** [comment]
> XAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

Getting this too

**Comment by CodingReaper1** [comment]
it doesnt work for me i installed alpha version but still get same error Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

**Comment by RayRizzling** [comment]
thank you, great job @eps1lon & @ckifer alpha is woking without any problems so far (we use it with r18).

**Comment by uccnk** [comment]
@ckifer 

Thank you very much. The alpha works very well. Using react 18 here..

**Comment by FabricioAllves** [comment]
> Olá pessoal, acho que a instalação `v2.10.2`deve corrigir o aviso, então tente isto:
> 
> `npm install recharts@2.10.2`
> 
> [ATUALIZAÇÃO]: `v2.10.2`estava funcionando perfeitamente em uma versão React sob R18
> 
> Para versões do React acima de R18, isso funciona perfeitamente para mim`npm i recharts@2.13.0-alpha.1`

That works for me, thanks!

**Comment by elenamik** [comment]
thank you!

**Comment by ndegwamoche** [comment]
Alpha works perfect for me, thanks

**Comment by NuraiymMamatova** [comment]
> I'm going to close this since we have a path forwards to remove the errors
> 
> Solution is `npm i recharts@alpha` I will post back here again when R19 is out and I can release `2.13.0`, that will contain the alpha fixes.
> 
> Feel free to continue to report any issues found here (or R19 related [here](https://github.com/recharts/recharts/issues/4558))
> 
> Thanks all

It works perfect for me, thanks

**Comment by NafeesIS** [comment]
> i tried downloading alpha but it didnt work console error didnt go away Warning: XAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

npm i recharts@alpha

try this command

**Comment by austinyearlykim** [comment]
"Warning: XAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead."

`npm i recharts@alpha` removed the errors for me.  Thank you so much.

**Comment by krishna-cyber** [comment]
![image](https://github.com/user-attachments/assets/24bae907-8c22-4671-a4c0-48a2b3b8c579)
Look at this but why don't it works for in my case

**Comment by ckifer** [comment]
@krishna-cyber its going to be hard to tell from that alone. Delete your node_modules and make sure your react-is version matches your react version (npm ls react-is)

https://github.com/recharts/recharts/issues/3615#issuecomment-2130440670

**Comment by ckifer** [comment]
New alpha version released https://www.npmjs.com/package/recharts/v/2.13.0-alpha.5
Should be no impact to this issue, but FYI since a lot in this thread are on alpha 4

**Comment by dimitarpeltekov** [comment]
Hi all my charts are written using recharts, if I install the recharts alpha should i delete the normal recharts and should i change everywhere in my imports to recharts alpha?

**Comment by dimitarpeltekov** [comment]
Hi @ckifer , I updated to the v2.13.0-alpha.5 version and the warnings disappeared. However a problem came out which a vertical bar chart. When rendering the bar chart is getting bigger and bigger. Which is an unexpected behavior, normally a bar is around 40px however it became like 1000px or more. Downgrading to v2.13.0-alpha.3 , fixed all the issues, but yea i will drop a video to see the blue chart should be with 1 bar and smaller like it is in the picture.

 ![Capture](https://github.com/user-attachments/assets/5908f5c9-0787-478e-90ef-015e8dc3b890)

https://github.com/user-attachments/assets/dd343fc3-cb3c-4912-82d5-727c8767d7e5

**Comment by ckifer** [comment]
Thanks @dimitarpeltekov  I'll look into it. Do you mind making a reproduction in codesandbox?

**Comment by dimitarpeltekov** [comment]
https://codesandbox.io/p/sandbox/react-typescript-forked-6dy93v 
Idk for some reason can't compile it

**Comment by ckifer** [comment]
@dimitarpeltekov looks like things are working fine https://codesandbox.io/p/sandbox/react-typescript-forked-hn5jfn?workspaceId=7a1754d3-b261-47b1-9339-2aca93020961

I wouldn't use "px" in the strings when settings your recharts height and width, or strings at all for that matter unless the string is a percentage. Same result with alpha.3 and alpha.5

**Comment by dimitarpeltekov** [comment]
Funny thing is, that locally and in sandbox, is working fine with alpha.5, howeve when I built an image and change that image on Stage env. we have, the problem occur.

**Comment by ckifer** [comment]
Sounds like a cache problem. The react is override might not be working correctly in the stage env. I can't really help with that unfortunately

**Comment by jsdev-robin** [comment]
install this `npm i recharts@alpha` and solve your plm!

**Comment by bendela6** [comment]
## Potential Workaround:

```
import { XAxis } from 'recharts';

// Temporarily store the defaultProps 
const xAxisProps = XAxis.defaultProps; 
delete XAxis.defaultProps; 

```
in your component
```
<XAxis 
  {...xAxisProps} // Apply the original default props
  // ... your other props here 
/>
```

**Comment by ckifer** [comment]
Just upgrade to the alpha version, no need to hack around it yourself

**Comment by ckifer** [comment]
Released in 2.13. No need for alpha anymore 👍

**Comment by Santhoshkumar5645** [comment]
> FYI this also happens for the Tooltip component

Same Here! Any solutions?

**Comment by victorz** [comment]
> > FYI this also happens for the Tooltip component
> 
> Same Here! Any solutions?

> [Released in 2.13. No need for alpha anymore 👍](https://github.com/recharts/recharts/issues/3615#issuecomment-2407597181)

I guess install `recharts@^2.13`?

**Comment by jukkahuuskonen** [comment]
> > FYI this also happens for the Tooltip component
> 
> Same Here! Any solutions?

2.13 fixed everything for me.

Maybe you should read to the end of issue, to see if there are solutions already available before posting 'me too'-comments to already fixed problem.

Of course, if the problem persists after applying provided solution (upgrade to v2.13), then please mention that in your comments otherwise you will probably just waste time of people supporting the library by making them check the comments that already have solution given.
