### ISSUE TITLE
Scrollbar keeps appearing on load

### ISSUE THREAD

**Issue by dekkofilms** [recharts/recharts#705]
I feel this is a bug that I can't seem to pin down.

Currently, on load it sometimes is pretty glitchy, and there is this scrollbar that appears, and sometimes flashes, and it disappears as soon as my cursor hovers over the graph. I will have a screenshot below:

![screen shot 2017-05-24 at 8 28 54 am](https://cloud.githubusercontent.com/assets/14862852/26405564/5081c94e-405b-11e7-9e27-036a76a04be8.png)

Here is the chart, that is wrapped inside of a ResponsiveContainer component:

```
<ResponsiveContainer width="100%" height={250}>
  <BarChart data={this.state.data02}>
    <Bar dataKey='sales' fill='#8884d8'/>
    <Tooltip />
    <XAxis dataKey="date"/>
    <YAxis/>
  </BarChart>
</ResponsiveContainer>
```

Recharts version is: 0.22.4
Browser: Chrome on Mac

**Comment by arena** [comment]
+1 
Any word on a fix or a workaround for this?

**Comment by dekkofilms** [comment]
@arena I mean I did find some CSS hacky thing to get rid of them, but I would still love a better explanation or solution to this issue. Didn't want to waste so much of my day trying to work on it haha.

I found this div that is a sibling to the recharts-wrapper and it's two div children of the graph that has overflow set to scroll, and I just set it as hidden in the CSS. Not sure why there was a scroll there in the first place, and it hasn't impacted me changing it to hidden.

The one highlighted, and it's two children shown below:
![screen shot 2017-05-26 at 4 08 35 pm](https://cloud.githubusercontent.com/assets/14862852/26512758/aa8e6176-422d-11e7-925a-a2244d89d473.png)

**Comment by arena** [comment]
Thank you!

I put this in my main styles.css file. I don't feel super awesome about it but I'm very happy to not see that scroll bar anymore!!! :) 

/*******************************************************************************
ReCharts Fixed with Hacks
*******************************************************************************/

:global .recharts-responsive-container div:nth-child(2) {
  overflow: hidden !important;
}

:global .recharts-responsive-container div:nth-child(2) div {
  overflow: hidden !important;
}

**********************************************************************************
(Note: you probably don't need :global if you copy this hack...but we did)

**Comment by htanjo** [comment]
I have the same issue. This issue is caused by [react-resize-detector](https://github.com/maslianok/react-resize-detector), not recharts itself.
Reported here: https://github.com/maslianok/react-resize-detector/issues/6, but not fixed yet.

Anyway, @arena's workaround works. Thanks!

**Comment by JasonK97** [comment]
I know it's been 5 years, but any fix on the scrollbar still showing up? I've got that issue, but I'm also using styled-components and styled-system.
