### ISSUE TITLE
Style Reference Line Label

### ISSUE THREAD

**Issue by westoncolemanl** [recharts/recharts#817]
Request for documentation

I am unable to style the reference line label to match this example:
http://recharts.org/#/en-US/api/ReferenceLine

![image](https://user-images.githubusercontent.com/15603579/28835896-88d5d3a4-7719-11e7-8b40-3b950a06c17c.png)

It ends up looking like this:

![image](https://user-images.githubusercontent.com/15603579/28835912-9ad64e76-7719-11e7-8ad1-7e0afaecf925.png)

I tried passing a ReactComponent into the label props. The result is no that no label gets displayed.

My code looked like
`
    <ReferenceLine
        x={firstQuadPercentile}
        stroke={'green'}
        label={<text>{'25th percentile'}</text>}
    />
`

and

`
    <ReferenceLine
        x={firstQuadPercentile}
        stroke={'green'}
        label={<div>{'25th percentile'}</div>}
    />
`

Since no label gets displayed, it didn't seem like this solution would work.

How can I style the label to match the first example shown in this request?

My recharts version : 1.0.0-alpha.2

**Comment by Meerkat007** [comment]
+1

**Comment by xile611** [comment]
@westoncolemanl 

```jsx
<ReferenceLine x="Page C" stroke="red" label={{ value: 'Max PV PAGE', fill: 'red' }}/>
```

**Comment by wewoor** [comment]
@xile611 The label align is always center? Which attribute can effect? or I need to customize label element?

**Comment by botaifilip** [comment]
Need help with the alignment too

**Comment by wewoor** [comment]
@botaifilip I have implemented this feature by overwriting Reference Line component. so, you can try it.

**Comment by westoncolemanl** [comment]
@xile611 still doesn't work.
@wewoor can I see what you did?

**Comment by fengshuo** [comment]
same issue here

**Comment by wewoor** [comment]
@westoncolemanl @fengshuo 

The below is my custom ReferenceLabel component. you can try it.


```javascript
export function ReferenceLabel(props) {
    const { 
        fill, value, textAnchor, 
        fontSize, viewBox, dy, dx,
    } = props;
    const x = viewBox.width + viewBox.x + 20;
    const y = viewBox.y - 6;
    return (
        <text 
            x={x} y={y}
            dy={dy}
            dx={dx}
            fill={fill}
            fontSize={fontSize || 10} 
            textAnchor={textAnchor}>
            {value}
        </text>
    )
}
```

**Comment by xile611** [comment]
@wewoor @westoncolemanl 

You can try the props `position` of label.
```jsx
<ReferenceLine x="Page C" stroke="red" label={{ position: 'top',  value: 'Max PV PAGE', fill: 'red', fontSize: 14 }}/>
```

**Comment by Silviu-Marian** [comment]
Is there a way to make it stick to left or right? 

Basically making it act as a tooltip, its position would be depending on 
1. where the reference is located in the chart
2. the actual width of the label

**Comment by kvz** [comment]
> I can try implementing a position: 'auto'

That would be grand. I currently use vertical referencelines for annotation like: `Deploy x happened`, `Launch feature Y`, `Adwords campaign 1 started` to help us spot what caused trends. But if there are events close to each other they become unreadable.

Automatically shifting the labels vertically, or making them show only when hovering over the ReferenceLine would solve the problem for my use case, but I wouldn't know how to go about that.

**Comment by dkulakowska** [comment]
does anyone know how to influence positioning of the ReferenceLine? I need mine to be in the middle of a Bar in a BarChart (same as ReferenceDot), instead it is positioned on the left side. Any help would be appreciated!! 
<img width="1082" alt="screen shot 2018-09-28 at 12 12 54" src="https://user-images.githubusercontent.com/31188583/46427111-cb73d300-c740-11e8-8fe3-646643a128be.png">

**Comment by icesun** [comment]
> does anyone know how to influence positioning of the ReferenceLine? I need mine to be in the middle of a Bar in a BarChart (same as ReferenceDot), instead it is positioned on the left side. Any help would be appreciated!!

Same here. My ReferenceLine always aligned on the left of the bar. How can I put it to the center as shown in the example?

![image](https://user-images.githubusercontent.com/1003183/46988729-555a6d80-d13d-11e8-8f04-a8c262507f00.png)

**Comment by larrystone** [comment]
For even more flexibility, you can leverage `foreignObject` together with @wewoor solution above, you would have something like this

`const ReferenceLabel = (props) => {
  const {
    value,
    viewBox,
  } = props;
  const x = viewBox.x - (value.length * 3);
  const y = viewBox.y;
  return (
    <foreignObject x={x} y={y} width="100" height="400">
      <DIV xmlns="http://www.w3.org/1999/xhtml">
        <small>
          {value}
        </small>
      </DIV>
    </foreignObject>
  )
}`

Then use like so

`<ReferenceLine label={<ReferenceLabel  />} />`

NOTE: I'm styling with styled-components but you can style however you like

**Comment by gaurav5430** [comment]
I have tried to document the usage of foreignObject to customize Recharts components here: https://medium.com/@gaurav5430/exploring-recharts-using-foreignobject-to-render-custom-html-5c6b75d6207e?source=friends_link&sk=25d48302dcb8e017e8b89aec01e2937b

**Comment by talkohavy** [comment]
> @wewoor @westoncolemanl
> 
> You can try the props `position` of label.
> 
> ```js
> <ReferenceLine x="Page C" stroke="red" label={{ position: 'top',  value: 'Max PV PAGE', fill: 'red', fontSize: 14 }}/>
> ```

Small correction there. The fontSize? Doen't work.
You need to do:
`style:{fontSize: 14}`
instead.
Habe fun.
